### ISSUE TITLE
cannot import name filter_fragments

### ISSUE THREAD

**Issue by relyanow** [grocsvs/grocsvs#1]
I get the following error when trying to run grocsvs. It looks like filter_fragments isn't in the source code?

Traceback (most recent call last):
  File "/home/relyanow/bin/grocsvs", line 9, in <module>
    load_entry_point('grocsvs==0.1', 'console_scripts', 'grocsvs')()
  File "/home/relyanow/.local/lib/python2.7/site-packages/pkg_resources/**init**.py", line 542, in load_entry_point
    return get_distribution(dist).load_entry_point(group, name)
  File "/home/relyanow/.local/lib/python2.7/site-packages/pkg_resources/**init**.py", line 2569, in load_entry_point
    return ep.load()
  File "/home/relyanow/.local/lib/python2.7/site-packages/pkg_resources/**init**.py", line 2229, in load
    return self.resolve()
  File "/home/relyanow/.local/lib/python2.7/site-packages/pkg_resources/**init**.py", line 2235, in resolve
    module = **import**(self.module_name, fromlist=['**name**'], level=0)
  File "/home/relyanow/.local/lib/python2.7/site-packages/grocsvs/main.py", line 9, in <module>
    from grocsvs import options as svoptions
  File "/home/relyanow/.local/lib/python2.7/site-packages/grocsvs/options.py", line 9, in <module>
    from grocsvs.stages import constants
  File "/home/relyanow/.local/lib/python2.7/site-packages/grocsvs/stages/**init**.py", line 2, in <module>
    from grocsvs.stages import sample_info
  File "/home/relyanow/.local/lib/python2.7/site-packages/grocsvs/stages/sample_info.py", line 9, in <module>
    from grocsvs.stages import filter_fragments
ImportError: cannot import name filter_fragments

**Comment by nspies** [comment]
Sorry about that, you're correct, I forgot to upload that file. This should be fixed now. I'm also making a few changes to add hg38 compatibility but haven't finished testing that yet. Please let me know if you have any more issues running grocsvs.
