### ISSUE TITLE
Tabix version 0.2.5 installed is too old

### ISSUE THREAD

**Issue by simoncchu** [grocsvs/grocsvs#10]
Hi,
I get the "Tabix version 0.2.5 installed is too old" error. However, the version I installed in within samtools (1.3.1) which I think is almost the latest version. Any suggestion for this? Thank you.

-----------------------------------------------------------------------------------
1 chunks to run. Starting...
2017-09-14 21:29:43 - -- starting logging PreflightStep --
2017-09-14 21:29:43 - ERROR: ERROR: Tabix version 0.2.5 installed is too old (version 1.0 or greater required)
2017-09-14 21:29:43 - ========== Exception ==========
2017-09-14 21:29:43 - Traceback (most recent call last):
2017-09-14 21:29:43 -   File "local/grocsvs_env/lib/python2.7/site-packages/grocsvs/pipeline.py", line 87, in _run_chunk
2017-09-14 21:29:43 -     chunk.run()
2017-09-14 21:29:43 -   File "local/grocsvs_env/lib/python2.7/site-packages/grocsvs/stages/preflight.py", line 63, in run
2017-09-14 21:29:43 -     raise Exception("Preflight failed; please check the log file at {}".format(outpath))
2017-09-14 21:29:43 - Exception: Preflight failed; please check the log file at working/PreflightStep/preflight.txt
2017-09-14 21:29:43 -
2017-09-14 21:29:43 - Preflight failed; please check the log file at working/PreflightStep/preflight.txt
ERROR RUNNING STAGE 'Preflight': Preflight failed; please check the log file at working/PreflightStep/preflight.txt
Failed to complete the following steps:
logs/PreflightStep/PreflightStep
Traceback (most recent call last):
  File "local/grocsvs_env/bin/grocsvs", line 11, in <module>
    sys.exit(main())
  File "local/grocsvs_env/lib/python2.7/site-packages/grocsvs/main.py", line 185, in main
    run(options)
  File "local/grocsvs_env/lib/python2.7/site-packages/grocsvs/main.py", line 42, in run
    runner.run_stage(stage, stage_name)
  File "local/grocsvs_env/lib/python2.7/site-packages/grocsvs/pipeline.py", line 38, in run_stage
    self.launch(to_run, all_steps, stage, stage_name, restart)
  File "local/grocsvs_env/lib/python2.7/site-packages/grocsvs/pipeline.py", line 72, in launch
    "above for more information.").format(stage_name))
Exception: Stage Preflight failed to complete. Check the log files above for more information.

**Comment by nspies** [comment]
It looks like tabix is now being distributed as part of [htslib](http://www.htslib.org/download/), rather than samtools. Let me know if upgrading to the latest htslib still gives you an error.

**Comment by simoncchu** [comment]
It works with the latest htslib. Thank you.
