### ISSUE TITLE
Stage Combine Read Clouds failed to complete

### ISSUE THREAD

**Issue by simoncchu** [grocsvs/grocsvs#11]
Hi, 

I met this issue when running on one of the datasets (with same configuration the running succeeds on another dataset with similar coverage):

Failed to complete the following steps:
logs/CombineReadcloudsStep/CombineReadcloudsStep.1000QA25_A12.10x_1000QA25_A12
Traceback (most recent call last):
  File "/home/10x_grocsv/grocsvs_env/bin/grocsvs", line 11, in <module>
    sys.exit(main())
  File "/home/10x_grocsv/grocsvs_env/lib/python2.7/site-packages/grocsvs/main.py", line 185, in main
    run(options)
  File "/home/10x_grocsv/grocsvs_env/lib/python2.7/site-packages/grocsvs/main.py", line 42, in run
    runner.run_stage(stage, stage_name)
  File "/home/10x_grocsv/grocsvs_env/lib/python2.7/site-packages/grocsvs/pipeline.py", line 38, in run_stage
    self.launch(to_run, all_steps, stage, stage_name, restart)
  File "/home/10x_grocsv/grocsvs_env/lib/python2.7/site-packages/grocsvs/pipeline.py", line 72, in launch
    "above for more information.").format(stage_name))
Exception: Stage Combine Read Clouds failed to complete. Check the log files above for more information.

And the "logs/CombineReadcloudsStep/CombineReadcloudsStep.1000QA25_A12.10x_1000QA25_A12" file showed:
2017-09-16 22:51:57 - -- starting logging CombineReadcloudsStep.1000QA25_A12.10x_1000QA25_A12 --
2017-09-16 22:51:57 - Loading read clouds...

Any suggestion for solving the issue? Thank you.

**Comment by nspies** [comment]
Take a look at logs/CombineReadcloudsStep/CombineReadcloudsStep.1000QA25_A12.10x_1000QA25_A12.

If it’s not informative, please send the contents of that file, as well as the full command line you used to launch grocsvs and the config.json file.

If this is a cluster issue, you can re-start the pipeline using the same original command, and it will start by rerunning this failed step.



On Sep 18, 2017, at 1:44 PM, Reedwarbler <notifications@github.com<mailto:notifications@github.com>> wrote:


Hi,

I met this issue when running on one of the datasets (with same configuration the running succeeds on another dataset with similar coverage):

Failed to complete the following steps:
logs/CombineReadcloudsStep/CombineReadcloudsStep.1000QA25_A12.10x_1000QA25_A12
Traceback (most recent call last):
File "/home/10x_grocsv/grocsvs_env/bin/grocsvs", line 11, in
sys.exit(main())
File "/home/10x_grocsv/grocsvs_env/lib/python2.7/site-packages/grocsvs/main.py", line 185, in main
run(options)
File "/home/10x_grocsv/grocsvs_env/lib/python2.7/site-packages/grocsvs/main.py", line 42, in run
runner.run_stage(stage, stage_name)
File "/home/10x_grocsv/grocsvs_env/lib/python2.7/site-packages/grocsvs/pipeline.py", line 38, in run_stage
self.launch(to_run, all_steps, stage, stage_name, restart)
File "/home/10x_grocsv/grocsvs_env/lib/python2.7/site-packages/grocsvs/pipeline.py", line 72, in launch
"above for more information.").format(stage_name))
Exception: Stage Combine Read Clouds failed to complete. Check the log files above for more information.

And the "logs/CombineReadcloudsStep/CombineReadcloudsStep.1000QA25_A12.10x_1000QA25_A12" file showed:
2017-09-16 22:51:57 - -- starting logging CombineReadcloudsStep.1000QA25_A12.10x_1000QA25_A12 --
2017-09-16 22:51:57 - Loading read clouds...

Any suggestion for solving the issue? Thank you.

**Comment by simoncchu** [comment]
I don't think this is a cluster issue, as some of the groups (with same configuration and similar coverage) run successfully. But I will re-run to check. Here are the contents of the files:
 
1) log file content:
```
"logs/CombineReadcloudsStep/CombineReadcloudsStep.1000QA25_A12.10x_1000QA25_A12" file showed:
2017-09-16 22:51:57 - -- starting logging CombineReadcloudsStep.1000QA25_A12.10x_1000QA25_A12 --
2017-09-16 22:51:57 - Loading read clouds...
```

2) configuration content:
```
{
    "ref_fasta":"/n/data1/LongRanger/refdata-b37-2.1.0/fasta/genome.fa",
    "bwa_index":"/n/data1/LongRanger/refdata-b37-2.1.0/fasta/genome.fa",
    "samples":{
        "1000QA25_A12":[
            {
                "type":"TenXDataset",
                "bam":"/n/data1/Alignment_longranger_wgs/1000QA25_A12/outs/phased_possorted_bam.bam",
                "id":"10x_1000QA25_A12"
            }
        ]
    },
    "cluster_settings":{
        "cluster_type":"IPCluster",
        "processes":15,
        "cluster_options":{
            "scheduler":"lsf",
            "queue":"medium",
            "extra_params":{
                "mem":16
            }
        }
    }
}
```
3) Commands:
```
grocsvs 1000QA25_A12_remote.json
```

**Comment by simoncchu** [comment]
I re-run the program with larger memory. And the program failed at the same step.

**Comment by nspies** [comment]
Can you try re-running the pipeline on a compute node with the --local option? This will output all the useful information directly to the terminal — I imagine there’s something going wrong that we’re missing because it's ending up in the cluster log.

**Comment by nspies** [comment]
Closing this issue for lack of attention. Please re-open if this is still a problem.
