### ISSUE TITLE
Failed to refine breakpoints

### ISSUE THREAD

**Issue by fangli80** [grocsvs/grocsvs#12]
Hi, I have trouble runnning GROC-SVs. I met this message: 
============================== Refine Breakpoints ==============================
3 chunks to run. Starting...
2017-10-02 13:22:44 - -- starting logging RefineGridSearchBreakpointsStep.chr20.chr20 --
2017-10-02 13:22:44 - ========== Exception ==========
2017-10-02 13:22:44 - Traceback (most recent call last):
2017-10-02 13:22:44 -   File "/home/lifang/anaconda2/lib/python2.7/site-packages/grocsvs/pipeline.py", line 87, in _run_chunk
2017-10-02 13:22:44 -     chunk.run()
2017-10-02 13:22:44 -   File "/home/lifang/anaconda2/lib/python2.7/site-packages/grocsvs/stages/refine_grid_search_breakpoints.py", line 107, in run
2017-10-02 13:22:44 -     refined = refine_events(events, self.options, self.logger)
2017-10-02 13:22:44 -   File "/home/lifang/anaconda2/lib/python2.7/site-packages/grocsvs/stages/refine_grid_search_breakpoints.py", line 186, in refine_events
2017-10-02 13:22:44 -     good_bc_counts_by_dataset, barcode_frequencies_by_dataset = get_barcode_info(options)
2017-10-02 13:22:44 -   File "/home/lifang/anaconda2/lib/python2.7/site-packages/grocsvs/stages/refine_grid_search_breakpoints.py", line 313, in get_barcode_info
2017-10-02 13:22:44 -     barcode_frequencies /= barcode_frequencies.sum().astype(float)
2017-10-02 13:22:44 - AttributeError: 'long' object has no attribute 'astype'
2017-10-02 13:22:44 - 
2017-10-02 13:22:44 - 'long' object has no attribute 'astype'
ERROR RUNNING STAGE 'Refine Breakpoints': 'long' object has no attribute 'astype'
Failed to complete the following steps:
/home/lifang/projects/grocsvs/genome_r/logs/RefineGridSearchBreakpointsStep/RefineGridSearchBreakpointsStep.chr20.chr20
/home/lifang/projects/grocsvs/genome_r/logs/RefineGridSearchBreakpointsStep/RefineGridSearchBreakpointsStep.chr21.chr20
/home/lifang/projects/grocsvs/genome_r/logs/RefineGridSearchBreakpointsStep/RefineGridSearchBreakpointsStep.chr21.chr21
Traceback (most recent call last):
  File "/home/lifang/anaconda2/bin/grocsvs", line 11, in <module>
    sys.exit(main())
  File "/home/lifang/anaconda2/lib/python2.7/site-packages/grocsvs/main.py", line 185, in main
    run(options)
  File "/home/lifang/anaconda2/lib/python2.7/site-packages/grocsvs/main.py", line 42, in run
    runner.run_stage(stage, stage_name)
  File "/home/lifang/anaconda2/lib/python2.7/site-packages/grocsvs/pipeline.py", line 38, in run_stage
    self.launch(to_run, all_steps, stage, stage_name, restart)
  File "/home/lifang/anaconda2/lib/python2.7/site-packages/grocsvs/pipeline.py", line 72, in launch
    "above for more information.").format(stage_name))
Exception: Stage Refine Breakpoints failed to complete. Check the log files above for more information.

Also, there was a dumped core file of idba_ud . It was generated in the Prefight step. 
(The idba was downloaded from https://github.com/grocsvs/idba/releases/tag/1.1.3g1 and was installed according to the instructions.) 

Core was generated by `/home/lifang/software/grocsvs-0.2.5/idba-1.1.3g1/bin/idba_ud -r working/Preflig'.
Program terminated with signal 11, Segmentation fault.
#0  0x000000000040c14f in Scaffold(int, int) () at ../src/release/idba_ud.cpp:526
526	        scaffold_graph.FilterEdges(option.min_pairs, scaffold_graph.sd(level) * 4);
warning: File "/home/lifang/software/gcc-4.9.4/lib64/libstdc++.so.6.0.20-gdb.py" auto-loading has been declined by your `auto-load safe-path' set to "/usr/share/gdb/auto-load:/usr/lib/debug:/usr/bin/mono-gdb.py".
To enable execution of this file add
	add-auto-load-safe-path /home/lifang/software/gcc-4.9.4/lib64/libstdc++.so.6.0.20-gdb.py
line to your configuration file "/home/lifang/.gdbinit".
To completely disable this security protection add
	set auto-load safe-path /
line to your configuration file "/home/lifang/.gdbinit".
For more information about this security protection see the
"Auto-loading safe path" section in the GDB manual.  E.g., run from the shell:
	info "(gdb)Auto-loading safe path"

Thank you!

**Comment by nspies** [comment]
The first error is curious. What version of numpy are you using? Can you send me your sample info file (this is found at `[[...]]/results/SampleInfoStep/sample_info.[[sample_name]].pickle`)?

I'm not sure what is causing the second error. If you try running idba_ud on a random fasta, what happens? For example:

```
>read1
ACGTGGCGAGACGTGGCGAGACGTGGCGAGACGTGGCGAGACGTGGCGAGACGTGGCGAGACGTGGCGAGACGTGGCGAGACGTGGCGAGACGTGGCGAGACGTGGCGAGACGTGGCGAGACGTGGCGAGACGTGGCGAGACGTGGCGAGACGTGGCGAG
>read2
GGACGACCCAGGACGACCCAGGACGACCCAGGACGACCCAGGACGACCCAGGACGACCCAGGACGACCCAGGACGACCCAGGACGACCCAGGACGACCCAGGACGACCCAGGACGACCCAGGACGACCCAGGACGACCCAGGACGACCCAGGACGACCCA
```

**Comment by fangli80** [comment]
Hi, thanks for your help. I am using numpy version 1.12.1
the sample info file is here: 
[sample_info.na12878.pickle.zip](https://github.com/grocsvs/grocsvs/files/1350576/sample_info.na12878.pickle.zip)

For the second error, I run idba_ud on the fasta file you gave and met this:

$ /home/lifang/software/grocsvs-0.2.5/idba-1.1.3g1/bin/idba_ud -r test.fa 
number of threads 8
reads 2
long reads 0
extra reads 0
read_length 160
kmer 20
kmers 20 20
merge bubble 0
contigs: 2 n50: 29 max: 29 mean: 29 total length: 58 n80: 29
aligned 0 reads
confirmed bases: 0 correct reads: 0 bases: 0
distance mean -nan sd -nan
invalid insert distance
kmer 40
kmers 20 20
merge bubble 0
contigs: 2 n50: 49 max: 49 mean: 49 total length: 98 n80: 49
aligned 0 reads
confirmed bases: 0 correct reads: 0 bases: 0
distance mean -nan sd -nan
invalid insert distance
kmer 60
kmers 20 20
merge bubble 0
contigs: 2 n50: 69 max: 69 mean: 69 total length: 138 n80: 69
aligned 0 reads
confirmed bases: 0 correct reads: 0 bases: 0
distance mean -nan sd -nan
invalid insert distance
kmer 80
kmers 20 20
merge bubble 0
contigs: 2 n50: 89 max: 89 mean: 89 total length: 178 n80: 89
aligned 0 reads
confirmed bases: 0 correct reads: 0 bases: 0
distance mean -nan sd -nan
invalid insert distance
kmer 100
kmers 20 20
merge bubble 0
contigs: 2 n50: 109 max: 109 mean: 109 total length: 218 n80: 109
reads 2
aligned 0 reads
distance mean -nan sd -nan
invalid insert distance
Segmentation fault

**Comment by fangli80** [comment]
I solved the first issue. 'astype' is an attribute of numpy array. In my case,  barcode_frequencies.sum() returns a single long integer, not a numpy array. 
So I changed the code to: `barcode_frequencies /= numpy (barcode_frequencies.sum()).astype(float)` .

**Comment by fangli80** [comment]
It seems that in real cases (for example, for a cluster of reads that may support a breakpoint), the second error does not happen.

**Comment by nspies** [comment]
Great, thanks for tracking this down on your own. Please let me know if further issues arise.
