### ISSUE TITLE
Too many open files

### ISSUE THREAD

**Issue by fangli80** [grocsvs/grocsvs#16]
Hi, 
I have this error while running GROCSVS:

cat logs/BarcodeOverlapsStep/BarcodeOverlapsStep.genome_repeat43.genome_repeat43.chr12.chr4.2.3
2018-03-03 18:46:31 - -- starting logging BarcodeOverlapsStep.genome_repeat43.genome_repeat43.chr12.chr4.2.3 --
2018-03-03 18:46:31 - ========== Exception ==========
2018-03-03 18:46:31 - Traceback (most recent call last):
2018-03-03 18:46:31 -   File "/home/fangl/anaconda2/lib/python2.7/site-packages/grocsvs/pipeline.py", line 87, in _run_chunk
2018-03-03 18:46:31 -   File "/home/fangl/anaconda2/lib/python2.7/site-packages/grocsvs/stages/barcode_overlaps.py", line 103, in run
2018-03-03 18:46:31 -   File "/home/fangl/anaconda2/lib/python2.7/site-packages/grocsvs/stages/barcode_overlaps.py", line 132, in get_bcwindows
2018-03-03 18:46:31 - IOError: [Errno 24] Too many open files: 'results/WindowBarcodesStep/bcwindows.genome_repeat43.genome_repeat43.chr12.2.pickle'
2018-03-03 18:46:31 - 
2018-03-03 18:46:31 - [Errno 24] Too many open files: 'results/WindowBarcodesStep/bcwindows.genome_repeat43.genome_repeat43.chr12.2.pickle'

line 132 of the barcode_overlaps.py file is: 
bcwindowsx = utilities.pickle.load(open(
            input_pathx["bcwindows"]))

Can you please help solve it?

**Comment by nspies** [comment]
It'd be helpful to have a few more details here. Because that step doesn't actually open a lot of files itself, I'm assuming you're running this in multiprocessing mode, is that correct?

What is the genome you're analyzing? How many contigs does it have?

**Comment by fangli80** [comment]
I am running on a human genome and using 12 threads. This error happens in the BarcodeOverlapsStep. It seems that it split the human genome into many regions and was doing a region to region comparison.

**Comment by nspies** [comment]
I don't think you should be opening an unreasonable number of files during this step, at most a few dozen. You could check your operating system's limits on number of open files (eg ulimit/maxfiles/etc, depending on OS) and try increasing this (if the default setting is 256, maybe try a few thousand), or you could try running with fewer threads.

**Comment by fangli80** [comment]
I am using Centos 7.4, both ulimit and /proc/sys/fs/file-max is 131072. I will try running with one thread

**Comment by fangli80** [comment]
Hi, 
I can go through the BarcodeOverlapsStep by increasing the system's limits. But I have another error, can you please have a look?  

cat logs/RefineGridSearchBreakpointsStep/RefineGridSearchBreakpointsStep.chr1.chr1 
2018-03-09 00:48:21 - -- starting logging RefineGridSearchBreakpointsStep.chr1.chr1 --
2018-03-09 00:48:22 - ========== Exception ==========
2018-03-09 00:48:22 - Traceback (most recent call last):
2018-03-09 00:48:22 -   File "/share/home/lifang/anaconda2/lib/python2.7/site-packages/grocsvs/pipeline.py", line 87, in _run_chunk
2018-03-09 00:48:22 -     chunk.run()
2018-03-09 00:48:22 -   File "/share/home/lifang/anaconda2/lib/python2.7/site-packages/grocsvs/stages/refine_grid_search_breakpoints.py", line 107, in run
2018-03-09 00:48:22 -     refined = refine_events(events, self.options, self.logger)
2018-03-09 00:48:22 -   File "/share/home/lifang/anaconda2/lib/python2.7/site-packages/grocsvs/stages/refine_grid_search_breakpoints.py", line 186, in refine_events
2018-03-09 00:48:22 -     good_bc_counts_by_dataset, barcode_frequencies_by_dataset = get_barcode_info(options)
2018-03-09 00:48:22 -   File "/share/home/lifang/anaconda2/lib/python2.7/site-packages/grocsvs/stages/refine_grid_search_breakpoints.py", line 313, in get_barcode_info
2018-03-09 00:48:22 -     barcode_frequencies /= barcode_frequencies.sum().astype(float)
2018-03-09 00:48:22 - AttributeError: 'long' object has no attribute 'astype'
2018-03-09 00:48:22 - 
2018-03-09 00:48:22 - 'long' object has no attribute 'astype'

**Comment by nspies** [comment]
Can you try pulling from the bc_freq_sum branch (https://github.com/grocsvs/grocsvs/tree/bc_freq_sum) and trying again?

**Comment by nspies** [comment]
Please let me know if this fixed your issue.

**Comment by fangli80** [comment]
Hi, 
Sorry for replying late. I have pulled from the bc_freq_sum branch. Can I continue the run by resubmitting the job or should I run the job from the beginning? 

I tried to continue the run by resubmitting the job (using the bc_freq_sum branch). I meet the following errors: 

```
2018-03-30 17:35:13 - ========== Exception ==========
2018-03-30 17:35:13 - Traceback (most recent call last):
2018-03-30 17:35:13 -   File "/share/home/lifang/anaconda2/lib/python2.7/site-packages/grocsvs/pipeline.py", line 87, in _run_chunk
2018-03-30 17:35:13 -     chunk.run()
2018-03-30 17:35:13 -   File "/share/home/lifang/anaconda2/lib/python2.7/site-packages/grocsvs/stages/cluster_svs.py", line 63, in run
2018-03-30 17:35:13 -     graph = self.prune_graph(graph)
2018-03-30 17:35:13 -   File "/share/home/lifang/anaconda2/lib/python2.7/site-packages/grocsvs/stages/cluster_svs.py", line 83, in prune_graph
2018-03-30 17:35:13 -     fixed = graphing.fix_breakpoints(self.options, pruned)
2018-03-30 17:35:13 -   File "/share/home/lifang/anaconda2/lib/python2.7/site-packages/grocsvs/graphing.py", line 240, in fix_breakpoints
2018-03-30 17:35:13 -     n1y = edge_for_node(n1x)
2018-03-30 17:35:13 -   File "/share/home/lifang/anaconda2/lib/python2.7/site-packages/grocsvs/graphing.py", line 226, in edge_for_node
2018-03-30 17:35:13 -     if _edges[0][0] == _node:
2018-03-30 17:35:13 - TypeError: 'EdgeDataView' object does not support indexing
2018-03-30 17:35:13 - 
2018-03-30 17:35:13 - 'EdgeDataView' object does not support indexing
Failed to complete the following steps:
logs/ClusterSVsStep/ClusterSVsStep
```

```
ERROR RUNNING STAGE 'Cluster SVs': 'EdgeDataView' object does not support indexing
Traceback (most recent call last):
  File "/share/home/lifang/anaconda2/bin/grocsvs", line 11, in <module>
    load_entry_point('grocsvs==0.2.6', 'console_scripts', 'grocsvs')()
  File "/share/home/lifang/anaconda2/lib/python2.7/site-packages/grocsvs/main.py", line 185, in main
    run(options)
  File "/share/home/lifang/anaconda2/lib/python2.7/site-packages/grocsvs/main.py", line 42, in run
    runner.run_stage(stage, stage_name)
  File "/share/home/lifang/anaconda2/lib/python2.7/site-packages/grocsvs/pipeline.py", line 38, in run_stage
    self.launch(to_run, all_steps, stage, stage_name, restart)
  File "/share/home/lifang/anaconda2/lib/python2.7/site-packages/grocsvs/pipeline.py", line 72, in launch
    "above for more information.").format(stage_name))
Exception: Stage Cluster SVs failed to complete. Check the log files above for more information.
```

**Comment by nspies** [comment]
Yes, you can re-run the pipeline and it will restart the last step that has not completed successfully.

The latest version of grocsvs on github (https://github.com/grocsvs/grocsvs/commit/6a199593393f411b6a9d56f678d8e2e8a2487c17) should fix your latest problem (though I am currently testing this). You can simply pull from the master branch.

**Comment by fangli80** [comment]
Ok. Thank you!
