### ISSUE TITLE
Doesn't work correctly whe absolute path to the reference is specified

### ISSUE THREAD

**Issue by 1dayac** [grocsvs/grocsvs#17]
Hi, guys, I've faced really weird bug - 
first, I've specified fasta_ref parameter as /home/dmeleshko/genome/genome.fa
and CallReadClouds step was shallow and next step raises an error. I dug through the code and found that if I create a link to genome.fa in config.json folder and it worked well. It seems that 

self.fasta = pyfaidx.Fasta(path, as_raw=True)

in reference.py doesn't work well because self.fasta is empty when the path is absolute. However, it works with any type of paths with your example. So, I'm not sure what to do here. Maybe you can specify that reference should be present in the same folder as config file?

**Comment by nspies** [comment]
I'm a bit confused here, as I use absolute paths for all the paths specified in the config.json file. What led you to believe that links and relative paths would work for you when the absolute path doesn't? Can you share the full config.json file contents and the error logs you got when you tried to run with absolute paths?

**Comment by 1dayac** [comment]
I agree that it sounds strange. It seems that this is pyfaidx internal error, I will try to debug their code. Shouldn't be very problematic and I will write when find out.

I've faced another problem during Cluster SVs step 

2018-03-20 12:23:52 - ========== Exception ==========
2018-03-20 12:23:52 - Traceback (most recent call last):
2018-03-20 12:23:52 -   File "/home/dmeleshko/chm13/grocsv/grocsvs_env/lib/python2.7/site-packages/grocsvs/pipeline.py", line 88, in _run_chunk
2018-03-20 12:23:52 -     chunk.run()
2018-03-20 12:23:52 -   File "/home/dmeleshko/chm13/grocsv/grocsvs_env/lib/python2.7/site-packages/grocsvs/stages/cluster_svs.py", line 63, in run
2018-03-20 12:23:52 -     graph = self.prune_graph(graph)
2018-03-20 12:23:52 -   File "/home/dmeleshko/chm13/grocsv/grocsvs_env/lib/python2.7/site-packages/grocsvs/stages/cluster_svs.py", line 83, in prune_graph
2018-03-20 12:23:52 -     fixed = graphing.fix_breakpoints(self.options, pruned)
2018-03-20 12:23:52 -   File "/home/dmeleshko/chm13/grocsv/grocsvs_env/lib/python2.7/site-packages/grocsvs/graphing.py", line 244, in fix_breakpoints
2018-03-20 12:23:52 -     n1y = edge_for_node(n1x)
2018-03-20 12:23:52 -   File "/home/dmeleshko/chm13/grocsv/grocsvs_env/lib/python2.7/site-packages/grocsvs/graphing.py", line 229, in edge_for_node
2018-03-20 12:23:52 -     print(_edges[0])
2018-03-20 12:23:52 - TypeError: 'EdgeDataView' object does not support indexing
2018-03-20 12:23:52 - 
2018-03-20 12:23:52 - 'EdgeDataView' object does not support indexing
ERROR RUNNING STAGE 'Cluster SVs': 'EdgeDataView' object does not support indexing

**Comment by nspies** [comment]
Just realized I failed to respond to the second issue here -- this problem should be fixed in the latest version of grocsvs.
