### ISSUE TITLE
Stage Genotyping failed to complete

### ISSUE THREAD

**Issue by zkalender** [grocsvs/grocsvs#20]
Hello, 
I have an issue on Stage Genotyping, here is the error I get:  

```
logs/GenotypingStep/GenotypingStep.105
logs/GenotypingStep/GenotypingStep.106
logs/GenotypingStep/GenotypingStep.107
logs/GenotypingStep/GenotypingStep.108
Exception AttributeError: "'NoneType' object has no attribute 'terminate'" in <Finalize object, dead> ignored
Traceback (most recent call last):
  File "/user/leuven/303/vsc30324/.local/bin/grocsvs", line 11, in <module>
    load_entry_point('grocsvs==0.2.6', 'console_scripts', 'grocsvs')()
  File "/user/leuven/303/vsc30324/.local/lib/python2.7/site-packages/grocsvs/main.py", line 185, in main
    run(options)
  File "/user/leuven/303/vsc30324/.local/lib/python2.7/site-packages/grocsvs/main.py", line 42, in run
    runner.run_stage(stage, stage_name)
  File "/user/leuven/303/vsc30324/.local/lib/python2.7/site-packages/grocsvs/pipeline.py", line 38, in run_stage
    self.launch(to_run, all_steps, stage, stage_name, restart)
  File "/user/leuven/303/vsc30324/.local/lib/python2.7/site-packages/grocsvs/pipeline.py", line 72, in launch
    "above for more information.").format(stage_name))
Exception: Stage Genotyping failed to complete. Check the log files above for more information.

```
GenotypingStep.108 doesn't exist in logs/GenotypingStep/ folder, but I checked the ones that are there. Most of them contains this: 

```
2018-05-05 16:25:44 - -- starting logging GenotypingStep.16 --
2018-05-05 16:25:44 - Genotyping...
2018-05-05 16:26:20 - Detecting segmental duplications...
2018-05-05 16:26:55 - -> finished running step; time elapsed: 0:01:11.325771
2018-05-05 16:26:55 - -- stopping logging --
```

But I also saw this one: 

```
2018-05-05 16:27:11 - -- starting logging GenotypingStep.54 --
2018-05-05 16:27:11 - Genotyping...
2018-05-05 16:27:45 - Detecting segmental duplications...
2018-05-05 16:28:07 - ========== Exception ==========
2018-05-05 16:28:07 - Traceback (most recent call last):
2018-05-05 16:28:07 -   File "/user/leuven/303/vsc30324/.local/lib/python2.7/site-packages/grocsvs/pipeline.py", line 87, in _run_chunk
2018-05-05 16:28:07 -     chunk.run()
2018-05-05 16:28:07 -   File "/user/leuven/303/vsc30324/.local/lib/python2.7/site-packages/grocsvs/stages/genotyping.py", line 112, in run
2018-05-05 16:28:07 -     compare_to_blacklist(genotypes, self.options)
2018-05-05 16:28:07 -   File "/user/leuven/303/vsc30324/.local/lib/python2.7/site-packages/grocsvs/stages/genotyping.py", line 199, in compare_to_blacklist
2018-05-05 16:28:07 -     blacklist_bed = ensure_file_is_bed(blacklist_path)
2018-05-05 16:28:07 -   File "/user/leuven/303/vsc30324/.local/lib/python2.7/site-packages/grocsvs/stages/genotyping.py", line 244, in ensure_file_is_bed
2018-05-05 16:28:07 -     return pybedtools.BedTool.from_dataframe(bed).sort()
2018-05-05 16:28:07 -   File "/user/leuven/303/vsc30324/.local/lib/python2.7/site-packages/pybedtools/bedtool.py", line 806, in decorated
2018-05-05 16:28:07 -     result = method(self, *args, **kwargs)
2018-05-05 16:28:07 -   File "/user/leuven/303/vsc30324/.local/lib/python2.7/site-packages/pybedtools/bedtool.py", line 337, in wrapped
2018-05-05 16:28:07 -     decode_output=decode_output,
2018-05-05 16:28:07 -   File "/user/leuven/303/vsc30324/.local/lib/python2.7/site-packages/pybedtools/helpers.py", line 380, in call_bedtools
2018-05-05 16:28:07 -     print('\n\t' + '\n\t'.join(problems[err.errno]))
2018-05-05 16:28:07 - KeyError: 11
2018-05-05 16:28:07 -
2018-05-05 16:28:07 - 11
```

Here is my config file: 

```
{
    "ref_fasta":"/staging/leuven/stg_00002/lcb/resources/longranger/refdata-GRCh38-2.1.0/fasta/genome.fa",
    "bwa_index":"/user/leuven/303/vsc30324/lcb/zkalender/resources/refdata-GRCh38-2.1.0/fasta/genome.fa",
    "blacklists":[
        "/user/leuven/303/vsc30324/lcb/zkalender/resources/refdata-GRCh38-2.1.0/regions/default_sv_blacklist.bed",
        "/user/leuven/303/vsc30324/lcb/zkalender/resources/refdata-GRCh38-2.1.0/regions/default_segdups.bedpe"
    ],
    "binaries": {
        "bwa": "/data/leuven/software/biomed/BWA/0.7.12-foss-2014a/bin/bwa"
    },
    "samples":{
        "Tumor":[
            {
                "type":"TenXDataset",
                "bam":"/user/leuven/303/vsc30324/lcb/zkalender/Runs/NovaSeq_Combined_Analysis/analysis/MM087/outs/phased_possorted_bam.bam",
                "id":"Tumor"
            }
        ]
    },
    "cluster_settings": {
        "cluster_type": "multiprocessing",
        "processes": 24}
        }
```

Greets,
Zeynep

**Comment by zkalender** [comment]
I re-run it later (when the server was less busy probably), and it worked.
