### ISSUE TITLE
False negatives?

### ISSUE THREAD

**Issue by lkhilton** [grocsvs/grocsvs#21]
I've just finished running groc-svs on a 30X coverage Chromium dataset, but it missed an SV that was called by longranger_wgs and has strong read support. Are there any parameters I can adjust when running groc-svs to try to reduce false negatives? One end of the breakpoint of the SV in question lies within a segmental duplication with highly similar paralogous genes, and we were hoping groc-svs could help resolve that end of the breakpoint.

**Comment by nspies** [comment]
Is this event a large-scale rearrangement? GROC-SVs uses a barcode approach that will only find events in the 10s of kb size, with best sensitivity at 50kb+. If you're looking at smaller events but wish to perform an assembly, let me know, I may be able to dig up some code to do this.

Assuming it's a larger event, can you check to see if there is a candidate event in the appropriate file in the SVCandidatesStep results directory? If it's not here, it's unlikely that the barcode signal will be strong enough to identify the event. Long Ranger also identifies events from short-read signal alone (if I recall correctly), whereas grocsvs performs detection using a barcode signal alone.

GROC-SVs shouldn't directly have a problem with seg dups, as it leaves the filtering of such up to the user. However, indirectly, this can lead to mapping issues in the short reads, making it difficult to align reads confidently within a seg dup and therefore making it difficult to enumerate the barcodes in that region. Are you giving GROC-SVs the barcode-aware alignments produced by lariat or EMerAld (http://cb.csail.mit.edu/cb/ema/)?

**Comment by lkhilton** [comment]
Thanks for your detailed response. 

The event in question is 66 kb. It doesn't appear in the SVCandidtesStep results dir. I've attached the Loupe barcode matrix for the event. The input file is the longranger_wgs phased_possorted_bam.bam file. 

We also performed hybridization capture of the region around the event, and I tried running GROC-SVs on that file as well. In that case, the event is found in the SVCandidatesStep results directory and in the CombineRefinedBreakpointsStep results dir, but GROC-SVs errored out at the ClusterSVsStep stage with the following error: 

```[lhilton@gphost06 ClusterSVsStep]$ cat ClusterSVsStep
2018-06-05 15:04:01 - -- starting logging ClusterSVsStep --
2018-06-05 15:04:01 - Loading data...
2018-06-05 15:04:01 - Building graph, pruning...
2018-06-05 15:04:02 - ========== Exception ==========
2018-06-05 15:04:02 - Traceback (most recent call last):
2018-06-05 15:04:02 -   File "build/bdist.linux-x86_64/egg/grocsvs/pipeline.py", line 87, in _run_chunk
2018-06-05 15:04:02 -     chunk.run()
2018-06-05 15:04:02 -   File "build/bdist.linux-x86_64/egg/grocsvs/stages/cluster_svs.py", line 74, in run
2018-06-05 15:04:02 -     table = graphing.graphs_to_table(graphs)
2018-06-05 15:04:02 -   File "build/bdist.linux-x86_64/egg/grocsvs/graphing.py", line 180, in graphs_to_table
2018-06-05 15:04:02 -     table = pandas.concat(tables).reset_index(drop=True)
2018-06-05 15:04:02 -   File "/home/lhilton/miniconda3/envs/grocsvs/lib/python2.7/site-packages/pandas/tools/merge.py", line 1451, in concat
2018-06-05 15:04:02 -     copy=copy)
2018-06-05 15:04:02 -   File "/home/lhilton/miniconda3/envs/grocsvs/lib/python2.7/site-packages/pandas/tools/merge.py", line 1484, in __init__
2018-06-05 15:04:02 -     raise ValueError('No objects to concatenate')
2018-06-05 15:04:02 - ValueError: No objects to concatenate
2018-06-05 15:04:02 -
2018-06-05 15:04:02 - No objects to concatenate
```

![loupe-sv-barcode-matrix 2](https://user-images.githubusercontent.com/36017879/41054787-39fbd794-6974-11e8-8216-dadb3ed96e8d.png)

Any ideas what could be causing this error? Is it because it's capture data?

**Comment by nspies** [comment]
Hrm, I'm not sure why the capture data would make it that far and then fail. This is probably a bug. Can you send me your CombineRefinedBreakpointsStep results? Feel free to email me if you'd prefer: nspies@stanford.edu

**Comment by lkhilton** [comment]
Just emailed the results. Thanks.
