### ISSUE TITLE
ERROR RUNNING STAGE 'Combine Read Clouds': No objects to concatenate

### ISSUE THREAD

**Issue by bbyrns** [grocsvs/grocsvs#24]
Hello,
I'm having an issue with the Combine Read Clouds stage using the following command:
`grocsvs config.json`
All bam files are the output of Longranger align runs.
I get the following error (**see below for config and log output**):
`============================== Preflight ==============================
--> 0 chunks need to be run. Skipping...

============================== Constants ==============================
--> 0 chunks need to be run. Skipping...

============================== Estimate Read Cloud Parameters ==============================
--> 0 chunks need to be run. Skipping...

============================== Call Read Clouds ==============================
--> 0 chunks need to be run. Skipping...

============================== Combine Read Clouds ==============================
6 chunks to run. Starting...
2019-01-04 14:01:59 - -- starting logging CombineReadcloudsStep.CS.CS --
2019-01-04 14:01:59 - Loading read clouds...
2019-01-04 14:01:59 - -- starting logging CombineReadcloudsStep.Jagger.Jagger --
2019-01-04 14:01:59 - Loading read clouds...
2019-01-04 14:01:59 - ========== Exception ==========
2019-01-04 14:01:59 - Traceback (most recent call last):
2019-01-04 14:01:59 -   File "/home/brook/src/grocsvs/grocsvs_env/local/lib/python2.7/site-packages/grocsvs/pipeline.py", line 87, in _run_chunk
2019-01-04 14:01:59 -     chunk.run()
2019-01-04 14:01:59 -   File "/home/brook/src/grocsvs/grocsvs_env/local/lib/python2.7/site-packages/grocsvs/stages/call_readclouds.py", line 66, in run
2019-01-04 14:01:59 -     readclouds = pandas.concat(readclouds)
2019-01-04 14:01:59 -   File "/home/brook/src/grocsvs/grocsvs_env/local/lib/python2.7/site-packages/pandas/core/reshape/concat.py", line 225, in concat
2019-01-04 14:01:59 -     copy=copy, sort=sort)
2019-01-04 14:01:59 -   File "/home/brook/src/grocsvs/grocsvs_env/local/lib/python2.7/site-packages/pandas/core/reshape/concat.py", line 259, in __init__
2019-01-04 14:01:59 -     raise ValueError('No objects to concatenate')
2019-01-04 14:01:59 - ValueError: No objects to concatenate
2019-01-04 14:01:59 - 
2019-01-04 14:01:59 - No objects to concatenate
2019-01-04 14:01:59 - -- starting logging CombineReadcloudsStep.Julius.Julius --
2019-01-04 14:01:59 - Loading read clouds...
2019-01-04 14:01:59 - ========== Exception ==========
2019-01-04 14:01:59 - Traceback (most recent call last):
2019-01-04 14:01:59 -   File "/home/brook/src/grocsvs/grocsvs_env/local/lib/python2.7/site-packages/grocsvs/pipeline.py", line 87, in _run_chunk
2019-01-04 14:01:59 -     chunk.run()
2019-01-04 14:01:59 -   File "/home/brook/src/grocsvs/grocsvs_env/local/lib/python2.7/site-packages/grocsvs/stages/call_readclouds.py", line 66, in run
2019-01-04 14:01:59 -     readclouds = pandas.concat(readclouds)
2019-01-04 14:01:59 -   File "/home/brook/src/grocsvs/grocsvs_env/local/lib/python2.7/site-packages/pandas/core/reshape/concat.py", line 225, in concat
2019-01-04 14:01:59 -     copy=copy, sort=sort)
2019-01-04 14:01:59 -   File "/home/brook/src/grocsvs/grocsvs_env/local/lib/python2.7/site-packages/pandas/core/reshape/concat.py", line 259, in __init__
2019-01-04 14:01:59 -     raise ValueError('No objects to concatenate')
2019-01-04 14:01:59 - ValueError: No objects to concatenate
2019-01-04 14:01:59 - 
2019-01-04 14:01:59 - No objects to concatenate
2019-01-04 14:01:59 - -- starting logging CombineReadcloudsStep.Landmark.Landmark --
2019-01-04 14:01:59 - ========== Exception ==========
2019-01-04 14:01:59 - Traceback (most recent call last):
2019-01-04 14:01:59 -   File "/home/brook/src/grocsvs/grocsvs_env/local/lib/python2.7/site-packages/grocsvs/pipeline.py", line 87, in _run_chunk
2019-01-04 14:01:59 -     chunk.run()
2019-01-04 14:01:59 -   File "/home/brook/src/grocsvs/grocsvs_env/local/lib/python2.7/site-packages/grocsvs/stages/call_readclouds.py", line 66, in run
2019-01-04 14:01:59 -     readclouds = pandas.concat(readclouds)
2019-01-04 14:01:59 -   File "/home/brook/src/grocsvs/grocsvs_env/local/lib/python2.7/site-packages/pandas/core/reshape/concat.py", line 225, in concat
2019-01-04 14:01:59 -     copy=copy, sort=sort)
2019-01-04 14:01:59 -   File "/home/brook/src/grocsvs/grocsvs_env/local/lib/python2.7/site-packages/pandas/core/reshape/concat.py", line 259, in __init__
2019-01-04 14:01:59 -     raise ValueError('No objects to concatenate')
2019-01-04 14:01:59 - ValueError: No objects to concatenate
2019-01-04 14:01:59 - 
2019-01-04 14:01:59 - No objects to concatenate
2019-01-04 14:01:59 - Loading read clouds...
2019-01-04 14:01:59 - -- starting logging CombineReadcloudsStep.Norin61.Norin61 --
2019-01-04 14:01:59 - ========== Exception ==========
2019-01-04 14:01:59 - Traceback (most recent call last):
2019-01-04 14:01:59 -   File "/home/brook/src/grocsvs/grocsvs_env/local/lib/python2.7/site-packages/grocsvs/pipeline.py", line 87, in _run_chunk
2019-01-04 14:01:59 -     chunk.run()
2019-01-04 14:01:59 -   File "/home/brook/src/grocsvs/grocsvs_env/local/lib/python2.7/site-packages/grocsvs/stages/call_readclouds.py", line 66, in run
2019-01-04 14:01:59 -     readclouds = pandas.concat(readclouds)
2019-01-04 14:01:59 -   File "/home/brook/src/grocsvs/grocsvs_env/local/lib/python2.7/site-packages/pandas/core/reshape/concat.py", line 225, in concat
2019-01-04 14:01:59 -     copy=copy, sort=sort)
2019-01-04 14:01:59 -   File "/home/brook/src/grocsvs/grocsvs_env/local/lib/python2.7/site-packages/pandas/core/reshape/concat.py", line 259, in __init__
2019-01-04 14:01:59 -     raise ValueError('No objects to concatenate')
2019-01-04 14:01:59 - ValueError: No objects to concatenate
2019-01-04 14:01:59 - 
2019-01-04 14:01:59 - No objects to concatenate
2019-01-04 14:01:59 - Loading read clouds...
2019-01-04 14:01:59 - -- starting logging CombineReadcloudsStep.Stanley.Stanley --
Failed to complete the following steps:
logs/CombineReadcloudsStep/CombineReadcloudsStep.CS.CS
logs/CombineReadcloudsStep/CombineReadcloudsStep.Jagger.Jagger
logs/CombineReadcloudsStep/CombineReadcloudsStep.Julius.Julius
logs/CombineReadcloudsStep/CombineReadcloudsStep.Landmark.Landmark
logs/CombineReadcloudsStep/CombineReadcloudsStep.Norin61.Norin61
logs/CombineReadcloudsStep/CombineReadcloudsStep.Stanley.Stanley
2019-01-04 14:01:59 - ========== Exception ==========
2019-01-04 14:01:59 - Traceback (most recent call last):
2019-01-04 14:01:59 -   File "/home/brook/src/grocsvs/grocsvs_env/local/lib/python2.7/site-packages/grocsvs/pipeline.py", line 87, in _run_chunk
2019-01-04 14:01:59 -     chunk.run()
2019-01-04 14:01:59 - Loading read clouds...
2019-01-04 14:01:59 -   File "/home/brook/src/grocsvs/grocsvs_env/local/lib/python2.7/site-packages/grocsvs/stages/call_readclouds.py", line 66, in run
2019-01-04 14:01:59 -     readclouds = pandas.concat(readclouds)
2019-01-04 14:01:59 -   File "/home/brook/src/grocsvs/grocsvs_env/local/lib/python2.7/site-packages/pandas/core/reshape/concat.py", line 225, in concat
2019-01-04 14:01:59 -     copy=copy, sort=sort)
2019-01-04 14:01:59 -   File "/home/brook/src/grocsvs/grocsvs_env/local/lib/python2.7/site-packages/pandas/core/reshape/concat.py", line 259, in __init__
2019-01-04 14:01:59 -     raise ValueError('No objects to concatenate')
2019-01-04 14:01:59 - ValueError: No objects to concatenate
2019-01-04 14:01:59 - 
2019-01-04 14:01:59 - No objects to concatenate
2019-01-04 14:01:59 - ========== Exception ==========
2019-01-04 14:01:59 - Traceback (most recent call last):
2019-01-04 14:01:59 -   File "/home/brook/src/grocsvs/grocsvs_env/local/lib/python2.7/site-packages/grocsvs/pipeline.py", line 87, in _run_chunk
2019-01-04 14:01:59 -     chunk.run()
2019-01-04 14:01:59 -   File "/home/brook/src/grocsvs/grocsvs_env/local/lib/python2.7/site-packages/grocsvs/stages/call_readclouds.py", line 66, in run
2019-01-04 14:01:59 -     readclouds = pandas.concat(readclouds)
2019-01-04 14:01:59 -   File "/home/brook/src/grocsvs/grocsvs_env/local/lib/python2.7/site-packages/pandas/core/reshape/concat.py", line 225, in concat
2019-01-04 14:01:59 -     copy=copy, sort=sort)
2019-01-04 14:01:59 -   File "/home/brook/src/grocsvs/grocsvs_env/local/lib/python2.7/site-packages/pandas/core/reshape/concat.py", line 259, in __init__
2019-01-04 14:01:59 -     raise ValueError('No objects to concatenate')
2019-01-04 14:01:59 - ValueError: No objects to concatenate
2019-01-04 14:01:59 - 
2019-01-04 14:01:59 - No objects to concatenate
Traceback (most recent call last):
  File "/home/brook/src/grocsvs/grocsvs_env/bin/grocsvs", line 11, in <module>
    sys.exit(main())
  File "/home/brook/src/grocsvs/grocsvs_env/local/lib/python2.7/site-packages/grocsvs/main.py", line 185, in main
    run(options)
  File "/home/brook/src/grocsvs/grocsvs_env/local/lib/python2.7/site-packages/grocsvs/main.py", line 42, in run
    runner.run_stage(stage, stage_name)
  File "/home/brook/src/grocsvs/grocsvs_env/local/lib/python2.7/site-packages/grocsvs/pipeline.py", line 38, in run_stage
    self.launch(to_run, all_steps, stage, stage_name, restart)
  File "/home/brook/src/grocsvs/grocsvs_env/local/lib/python2.7/site-packages/grocsvs/pipeline.py", line 72, in launch
    "above for more information.").format(stage_name))
Exception: Stage Combine Read Clouds failed to complete. Check the log files above for more information.
`
**Here is my config file:**
`{
	"ref_fasta":"ASH_parts.fasta",
	"bwa_index":"/isilon/groups/wheat/10x/reference/refdata-ASH_parts/fasta/genome.fa",
	"binaries":{
		"bwa":"/usr/bin/bwa"
	},
	"samples":{
		"Landmark":[
			{
				"type":"TenXDataset",
				"bam":"/isilon/groups/wheat/10x/processed/Hexaploid-alignments/bams/Landmark_vs_ASH_parts.bam",
				"id":"Landmark"
			}
		],
		"Stanley":[
			{
				"type":"TenXDataset",
				"bam":"/isilon/groups/wheat/10x/processed/Hexaploid-alignments/bams/Stanley_vs_ASH_parts.bam",
				"id":"Stanley"
			}
		],
		"Norin61":[
			{
				"type":"TenXDataset",
				"bam":"/isilon/groups/wheat/10x/processed/Hexaploid-alignments/bams/Norin61_vs_ASH_parts.bam",
				"id":"Norin61"
			}
		],
		"Julius":[
			{
				"type":"TenXDataset",
				"bam":"/isilon/groups/wheat/10x/processed/Hexaploid-alignments/bams/Julius_vs_ASH_parts.bam",
				"id":"Julius"
			}
		],
		"Jagger":[
			{
				"type":"TenXDataset",
				"bam":"/isilon/groups/wheat/10x/processed/Hexaploid-alignments/bams/Jagger_vs_ASH_parts.bam",
				"id":"Jagger"
			}
		],
		"CS":[
			{
				"type":"TenXDataset",
				"bam":"/isilon/groups/wheat/10x/processed/Hexaploid-alignments/bams/CS_vs_ASH_parts.bam",
				"id":"CS"
			}
		]
	},
	"cluster_settings":{
		"cluster_type":"multiprocessing",
		"processes":120
	}
}
`
**Here is a log file from one sample (all samples have similar corresponding log output):**
`2019-01-04 14:01:59 - -- starting logging CombineReadcloudsStep.CS.CS --
2019-01-04 14:01:59 - Loading read clouds...
2019-01-04 14:01:59 - ========== Exception ==========
2019-01-04 14:01:59 - Traceback (most recent call last):
2019-01-04 14:01:59 -   File "/home/brook/src/grocsvs/grocsvs_env/local/lib/python2.7/site-packages/grocsvs/pipeline.py", line 87, in _run_chunk
2019-01-04 14:01:59 -     chunk.run()
2019-01-04 14:01:59 -   File "/home/brook/src/grocsvs/grocsvs_env/local/lib/python2.7/site-packages/grocsvs/stages/call_readclouds.py", line 66, in run
2019-01-04 14:01:59 -     readclouds = pandas.concat(readclouds)
2019-01-04 14:01:59 -   File "/home/brook/src/grocsvs/grocsvs_env/local/lib/python2.7/site-packages/pandas/core/reshape/concat.py", line 225, in concat
2019-01-04 14:01:59 -     copy=copy, sort=sort)
2019-01-04 14:01:59 -   File "/home/brook/src/grocsvs/grocsvs_env/local/lib/python2.7/site-packages/pandas/core/reshape/concat.py", line 259, in __init__
2019-01-04 14:01:59 -     raise ValueError('No objects to concatenate')
2019-01-04 14:01:59 - ValueError: No objects to concatenate
2019-01-04 14:01:59 - 
2019-01-04 14:01:59 - No objects to concatenate
`

**Comment by lebarsarthur** [comment]
I am having the same issue

Here is the log/stdout file:

```
============================== Preflight ==============================
1 chunks to run. Starting...
{
    "binaries": {
        "bwa": "/groups/supergene/tools/GROCSVS/grocsvs.conda/bin/bwa", 
        "idba_ud": "/groups/supergene/tools/GROCSVS/idba-1.1.3g1/bin/idba"
    }, 
    "blacklists": [], 
    "bwa_index": "/groups/supergene/tools/LONGRANGER/MKREF/2/out/refdata-Heliconius_melpomene_melpomene_Hmel2_-_scaffolds.fa/fasta/genome.fa", 
    "cluster_settings": {
        "cluster_options": {}, 
        "cluster_type": "multiprocessing", 
        "processes": 20
    }, 
    "debug": false, 
    "ref_fasta": "/groups/supergene/data/Heliconius_melpomene_melpomene_Hmel2_-_scaffolds.fa", 
    "samples": {
        "36": [
            {
                "bam": "/groups/supergene/tools/LONGRANGER/ALIGN_2/36/out/36/outs/possorted_bam.bam", 
                "id": "36", 
                "type": "TenXDataset"
            }
        ], 
        "37": [
            {
                "bam": "/groups/supergene/tools/LONGRANGER/ALIGN_2/37/out/37/outs/possorted_bam.bam", 
                "id": "37", 
                "type": "TenXDataset"
            }
        ], 
        "38": [
            {
                "bam": "/groups/supergene/tools/LONGRANGER/ALIGN_2/38/out/38/outs/possorted_bam.bam", 
                "id": "38", 
                "type": "TenXDataset"
            }
        ], 
        "40": [
            {
                "bam": "/groups/supergene/tools/LONGRANGER/ALIGN_2/40/out/40/outs/possorted_bam.bam", 
                "id": "40", 
                "type": "TenXDataset"
            }
        ]
    }
}
2019-03-04 14:32:05 - -- starting logging PreflightStep --
2019-03-04 14:32:05 - -> finished running step; time elapsed: 0:00:00.273001
2019-03-04 14:32:05 - -- stopping logging --
--> Preflight completed.

============================== Constants ==============================
1 chunks to run. Starting...
2019-03-04 14:32:05 - -- starting logging ConstantsStep --
2019-03-04 14:32:06 - -> finished running step; time elapsed: 0:00:00.104852
2019-03-04 14:32:06 - -- stopping logging --
--> Constants completed.

============================== Estimate Read Cloud Parameters ==============================
4 chunks to run. Starting...
2019-03-04 14:32:06 - -- starting logging EstimateReadCloudParamsStep.36.36 --
2019-03-04 14:32:06 - -- starting logging EstimateReadCloudParamsStep.37.37 --
2019-03-04 14:32:06 - -- starting logging EstimateReadCloudParamsStep.38.38 --
2019-03-04 14:32:06 - -- starting logging EstimateReadCloudParamsStep.40.40 --
2019-03-04 14:34:51 - 5753.0 47187.0 58024.0
2019-03-04 14:34:51 - 50000
2019-03-04 14:34:55 - -> finished running step; time elapsed: 0:02:49.498097
2019-03-04 14:34:55 - -- stopping logging --
2019-03-04 14:35:08 - 4727.0 43242.0 56771.797
2019-03-04 14:35:08 - 45000
2019-03-04 14:35:09 - 3330.0 36808.0 54330.0
2019-03-04 14:35:09 - 3120.0 35708.0 53796.0
2019-03-04 14:35:09 - 40000
2019-03-04 14:35:09 - 40000
2019-03-04 14:35:11 - -> finished running step; time elapsed: 0:03:05.701695
2019-03-04 14:35:11 - -- stopping logging --
2019-03-04 14:35:17 - -> finished running step; time elapsed: 0:03:10.914958
2019-03-04 14:35:17 - -- stopping logging --
2019-03-04 14:35:17 - -> finished running step; time elapsed: 0:03:10.918393
2019-03-04 14:35:17 - -- stopping logging --
--> Estimate Read Cloud Parameters completed.

============================== Call Read Clouds ==============================
--> 0 chunks need to be run. Skipping...

============================== Combine Read Clouds ==============================
4 chunks to run. Starting...
2019-03-04 14:35:17 - -- starting logging CombineReadcloudsStep.37.37 --
2019-03-04 14:35:17 - -- starting logging CombineReadcloudsStep.36.36 --
2019-03-04 14:35:17 - -- starting logging CombineReadcloudsStep.38.38 --
2019-03-04 14:35:17 - -- starting logging CombineReadcloudsStep.40.40 --
2019-03-04 14:35:18 - Loading read clouds...
2019-03-04 14:35:18 - Loading read clouds...
2019-03-04 14:35:18 - Loading read clouds...
2019-03-04 14:35:18 - Loading read clouds...
2019-03-04 14:35:18 - ========== Exception ==========
2019-03-04 14:35:18 - ========== Exception ==========
2019-03-04 14:35:18 - ========== Exception ==========
2019-03-04 14:35:18 - Traceback (most recent call last):
2019-03-04 14:35:18 - Traceback (most recent call last):
2019-03-04 14:35:18 - Traceback (most recent call last):
2019-03-04 14:35:18 -   File "/groups/supergene/tools/GROCSVS/grocsvs.conda/lib/python2.7/site-packages/grocsvs/pipeline.py", line 87, in _run_chunk
2019-03-04 14:35:18 -   File "/groups/supergene/tools/GROCSVS/grocsvs.conda/lib/python2.7/site-packages/grocsvs/pipeline.py", line 87, in _run_chunk
2019-03-04 14:35:18 -   File "/groups/supergene/tools/GROCSVS/grocsvs.conda/lib/python2.7/site-packages/grocsvs/pipeline.py", line 87, in _run_chunk
2019-03-04 14:35:18 -     chunk.run()
2019-03-04 14:35:18 -     chunk.run()
2019-03-04 14:35:18 -     chunk.run()
2019-03-04 14:35:18 -   File "/groups/supergene/tools/GROCSVS/grocsvs.conda/lib/python2.7/site-packages/grocsvs/stages/call_readclouds.py", line 66, in run
2019-03-04 14:35:18 -   File "/groups/supergene/tools/GROCSVS/grocsvs.conda/lib/python2.7/site-packages/grocsvs/stages/call_readclouds.py", line 66, in run
2019-03-04 14:35:18 -   File "/groups/supergene/tools/GROCSVS/grocsvs.conda/lib/python2.7/site-packages/grocsvs/stages/call_readclouds.py", line 66, in run
2019-03-04 14:35:18 -     readclouds = pandas.concat(readclouds)
2019-03-04 14:35:18 -     readclouds = pandas.concat(readclouds)
2019-03-04 14:35:18 -     readclouds = pandas.concat(readclouds)
2019-03-04 14:35:18 -   File "/groups/supergene/tools/GROCSVS/grocsvs.conda/lib/python2.7/site-packages/pandas/core/reshape/concat.py", line 228, in concat
2019-03-04 14:35:18 - ========== Exception ==========
2019-03-04 14:35:18 -   File "/groups/supergene/tools/GROCSVS/grocsvs.conda/lib/python2.7/site-packages/pandas/core/reshape/concat.py", line 228, in concat
2019-03-04 14:35:18 -   File "/groups/supergene/tools/GROCSVS/grocsvs.conda/lib/python2.7/site-packages/pandas/core/reshape/concat.py", line 228, in concat
2019-03-04 14:35:18 -     copy=copy, sort=sort)
2019-03-04 14:35:18 -     copy=copy, sort=sort)
2019-03-04 14:35:18 -     copy=copy, sort=sort)
2019-03-04 14:35:18 - Traceback (most recent call last):
2019-03-04 14:35:18 -   File "/groups/supergene/tools/GROCSVS/grocsvs.conda/lib/python2.7/site-packages/pandas/core/reshape/concat.py", line 262, in __init__
2019-03-04 14:35:18 -   File "/groups/supergene/tools/GROCSVS/grocsvs.conda/lib/python2.7/site-packages/pandas/core/reshape/concat.py", line 262, in __init__
2019-03-04 14:35:18 -   File "/groups/supergene/tools/GROCSVS/grocsvs.conda/lib/python2.7/site-packages/pandas/core/reshape/concat.py", line 262, in __init__
2019-03-04 14:35:18 -   File "/groups/supergene/tools/GROCSVS/grocsvs.conda/lib/python2.7/site-packages/grocsvs/pipeline.py", line 87, in _run_chunk
2019-03-04 14:35:18 -     raise ValueError('No objects to concatenate')
2019-03-04 14:35:18 -     raise ValueError('No objects to concatenate')
2019-03-04 14:35:18 -     raise ValueError('No objects to concatenate')
2019-03-04 14:35:18 -     chunk.run()
2019-03-04 14:35:18 - ValueError: No objects to concatenate
2019-03-04 14:35:18 - ValueError: No objects to concatenate
2019-03-04 14:35:18 - ValueError: No objects to concatenate
2019-03-04 14:35:18 -   File "/groups/supergene/tools/GROCSVS/grocsvs.conda/lib/python2.7/site-packages/grocsvs/stages/call_readclouds.py", line 66, in run
2019-03-04 14:35:18 - 
2019-03-04 14:35:18 - 
2019-03-04 14:35:18 - 
2019-03-04 14:35:18 -     readclouds = pandas.concat(readclouds)
2019-03-04 14:35:18 - No objects to concatenate
2019-03-04 14:35:18 - No objects to concatenate
2019-03-04 14:35:18 - No objects to concatenate
2019-03-04 14:35:18 -   File "/groups/supergene/tools/GROCSVS/grocsvs.conda/lib/python2.7/site-packages/pandas/core/reshape/concat.py", line 228, in concat
2019-03-04 14:35:18 -     copy=copy, sort=sort)
2019-03-04 14:35:18 -   File "/groups/supergene/tools/GROCSVS/grocsvs.conda/lib/python2.7/site-packages/pandas/core/reshape/concat.py", line 262, in __init__
2019-03-04 14:35:18 -     raise ValueError('No objects to concatenate')
2019-03-04 14:35:18 - ValueError: No objects to concatenate
2019-03-04 14:35:18 - 
2019-03-04 14:35:18 - No objects to concatenate
Failed to complete the following steps:
/groups/supergene/tools/GROCSVS/36-37-38-40/logs/CombineReadcloudsStep/CombineReadcloudsStep.36.36
/groups/supergene/tools/GROCSVS/36-37-38-40/logs/CombineReadcloudsStep/CombineReadcloudsStep.37.37
/groups/supergene/tools/GROCSVS/36-37-38-40/logs/CombineReadcloudsStep/CombineReadcloudsStep.38.38
/groups/supergene/tools/GROCSVS/36-37-38-40/logs/CombineReadcloudsStep/CombineReadcloudsStep.40.40
ERROR RUNNING STAGE 'Combine Read Clouds': No objects to concatenate
Traceback (most recent call last):
  File "/groups/supergene/tools/GROCSVS/grocsvs.conda/bin/grocsvs", line 10, in <module>
    sys.exit(main())
  File "/groups/supergene/tools/GROCSVS/grocsvs.conda/lib/python2.7/site-packages/grocsvs/main.py", line 185, in main
    run(options)
  File "/groups/supergene/tools/GROCSVS/grocsvs.conda/lib/python2.7/site-packages/grocsvs/main.py", line 42, in run
    runner.run_stage(stage, stage_name)
  File "/groups/supergene/tools/GROCSVS/grocsvs.conda/lib/python2.7/site-packages/grocsvs/pipeline.py", line 38, in run_stage
    self.launch(to_run, all_steps, stage, stage_name, restart)
  File "/groups/supergene/tools/GROCSVS/grocsvs.conda/lib/python2.7/site-packages/grocsvs/pipeline.py", line 72, in launch
    "above for more information.").format(stage_name))
Exception: Stage Combine Read Clouds failed to complete. Check the log files above for more information.
Hmel201002
Hmel201009
Hmel201011
Hmel202004
Hmel202006
Hmel203069
Hmel204001
Hmel204017
Hmel206006
Hmel206009
Hmel206019
Hmel207002
Hmel207021
Hmel209007
Hmel210004
Hmel210011
Hmel211002
Hmel211004
Hmel212001
Hmel212013
Hmel214008
Hmel215047
Hmel216011
Hmel217001
Hmel217004
Hmel217018
Hmel217020
Hmel218018
Hmel219003
Hmel219014
Hmel219018
Hmel220003
```

And my config.json file:

```
{  
    "ref_fasta":"/groups/supergene/data/Heliconius_melpomene_melpomene_Hmel2_-_scaffolds.fa",
    "bwa_index":"/groups/supergene/tools/LONGRANGER/MKREF/2/out/refdata-Heliconius_melpomene_melpomene_Hmel2_-_scaffolds.fa/fasta/genome.fa",
    "binaries":{
        "bwa":"/groups/supergene/tools/GROCSVS/grocsvs.conda/bin/bwa",
        "idba_ud":"/groups/supergene/tools/GROCSVS/idba-1.1.3g1/bin/idba"   
    },
    "samples": {  
        "36":[  
            {  
                "type":"TenXDataset",
                "bam":"/groups/supergene/tools/LONGRANGER/ALIGN_2/36/out/36/outs/possorted_bam.bam",
                "id":"36"
            }
        ],
        "37":[
            {
                "type":"TenXDataset",
                "bam":"/groups/supergene/tools/LONGRANGER/ALIGN_2/37/out/37/outs/possorted_bam.bam",
                "id":"37"
            }
        ],
        "38":[
            {
                "type":"TenXDataset",
                "bam":"/groups/supergene/tools/LONGRANGER/ALIGN_2/38/out/38/outs/possorted_bam.bam",
                "id":"38"
            }
        ],
        "40":[
            {
                "type":"TenXDataset",
                "bam":"/groups/supergene/tools/LONGRANGER/ALIGN_2/40/out/40/outs/possorted_bam.bam",
                "id":"40"
            }
        ]
    },
    "cluster_settings": {
        "cluster_type": "multiprocessing",
        "processes":20
    }
}
```

**Comment by nspies** [comment]
Hi both, and sorry for the slowness of my response -- I have taken my next job and don't have a whole lot of time for my post-doc projects :)

While I know of a few people who've used grocsvs on non-human chromosomes, I developed it with a strong focus around human genomes. You're hitting a problem where I tried to standardize chromosome name format ("chr13"<->"13") which breaks down when you have more exotic plant and animal genomes with chromosome names that don't follow this format. (The standardization code doesn't look to actually do a whole lot at the moment except break your genomes!)

I believe a few changes to the references module around [here](https://github.com/grocsvs/grocsvs/blob/master/src/grocsvs/reference.py#L16) should suffice to update grocsvs with support for arbitrary genomes.

Something like the following (untested) code should set you on the correct path:

```python
...
class Reference(object):
    def __init__(self, path, debug=False):
        self.path = path
        self.fasta = pyfaidx.Fasta(path, as_raw=True)
        self.debug = debug

        self.chroms_to_std_chroms = collections.OrderedDict()
        self.std_chroms_to_chroms = collections.OrderedDict()
        self.chrom_lengths = collections.OrderedDict()

        for chrom in self.fasta.keys():
            self.chrom_lengths[chrom] = len(self.fasta[chrom])

    @property
    def chroms(self):
        if self.debug:
            return ["chr20", "chr21"]

        return self.chrom_lengths.keys()

    def compare_chroms(self, chromx, chromy):
        return cmp(self.chroms.index(chromx), self.chroms.index(chromy))
...
```

(the above code would replace the existing `Reference` class).

I'm happy to accept a pull request if the above updates work for you.

**Comment by nspies** [comment]
Ah, actually, just realized that for many human genome assemblies, the existing code is important for filtering out the un-assigned contigs -- grocsvs chokes if there are too many contigs in the assembly.

You may need to adjust the above code to limit the number of contigs/chromosomes analyzed by grocsvs to something closer to dozens rather than hundreds.

**Comment by lebarsarthur** [comment]
I can confirm this works @nspies , thank you !

I'm not sure I'm following you about your second comment however, wouldn't I miss potential SVs if I do that ?

**Comment by nspies** [comment]
Great, glad that worked. 
The tail end of the contiguous distribution ends up being quite small chromosome fragments, at least in a high quality genome, but you’re right this might end up resulting in missed SV calls. In any case, I wouldn’t include contiguous that are on the order of the 10x fragment size, say less than half a megabase. 
    	
    	

    	
    
  




On Thu, Mar 7, 2019 at 9:39 AM -0500, "Mada2" <notifications@github.com> wrote:












I can confirm this works @nspies , thank you !


I'm not sure I'm following you about your second comment however, wouldn't I miss potential SVs if I do that ?

**Comment by lebarsarthur** [comment]
I see, can this limitation be done with GROCSVs by modifying some piece of code somewhere? Or can I only do this by trimming my genome beforehand and then realign?

Thanks again for your help @nspies

**Comment by nspies** [comment]
> I see, can this limitation be done with GROCSVs by modifying some piece of code somewhere? Or can I only do this by trimming my genome beforehand and then realign?

This isn't something that's supported at the moment, but you'll note that the reference file above does include the chromosome (contig) lengths so this could easily be used to filter the chromosomes that get loaded by grocsvs.
