### ISSUE TITLE
broken pipe error

### ISSUE THREAD

**Issue by sgreer77** [grocsvs/grocsvs#3]
I received this error while running grocsvs:

Traceback (most recent call last):
  File "/home/sgreer2/.conda/envs/grocsvs_env/bin/grocsvs", line 11, in <module>
    load_entry_point('grocsvs==0.1', 'console_scripts', 'grocsvs')()
  File "/home/sgreer2/.conda/envs/grocsvs_env/lib/python2.7/site-packages/grocsvs/main.py", line 175, in main
    run(options)
  File "/home/sgreer2/.conda/envs/grocsvs_env/lib/python2.7/site-packages/grocsvs/main.py", line 42, in run
    runner.run_stage(stage, stage_name)
  File "/home/sgreer2/.conda/envs/grocsvs_env/lib/python2.7/site-packages/grocsvs/pipeline.py", line 46, in run_stage
    jobmanagers.map(_run_chunk, to_run)
  File "/home/sgreer2/.conda/envs/grocsvs_env/lib/python2.7/site-packages/grocsvs/jobmanagers.py", line 13, in map
    fn(arg)
  File "/home/sgreer2/.conda/envs/grocsvs_env/lib/python2.7/site-packages/grocsvs/pipeline.py", line 71, in _run_chunk
    chunk.run()
  File "/home/sgreer2/.conda/envs/grocsvs_env/lib/python2.7/site-packages/grocsvs/stages/call_readclouds.py", line 84, in run
    readclouds.to_csv(bgzip_proc.stdin, sep="\t", index=False)
  File "/home/sgreer2/.conda/envs/grocsvs_env/lib/python2.7/site-packages/pandas/core/frame.py", line 1383, in to_csv
    formatter.save()
  File "/home/sgreer2/.conda/envs/grocsvs_env/lib/python2.7/site-packages/pandas/formats/format.py", line 1475, in save
    self._save()
  File "/home/sgreer2/.conda/envs/grocsvs_env/lib/python2.7/site-packages/pandas/formats/format.py", line 1576, in _save
    self._save_chunk(start_i, end_i)
  File "/home/sgreer2/.conda/envs/grocsvs_env/lib/python2.7/site-packages/pandas/formats/format.py", line 1602, in _save_chunk
    lib.write_csv_rows(self.data, ix, self.nlevels, self.cols, self.writer)
  File "pandas/lib.pyx", line 1171, in pandas.lib.write_csv_rows (pandas/lib.c:21083)
IOError: [Errno 32] Broken pipe

Any ideas how I might fix this issue? Thanks!

**Comment by nspies** [comment]
Can you try running it again?

**Comment by nspies** [comment]
closed by 1a31369ae1c8d6cb97cde9a3ec5ea281baedc3f4
