### ISSUE TITLE
'tuple' object has no attribute 'Index' in genotyping.py

### ISSUE THREAD

**Issue by chen42** [grocsvs/grocsvs#30]
Hi,

I am running grocsvs on a panel of 32 recombinant inbred rats to get a uniform genotype of SVs. However, I ran into this error message. Could you please see how to fix it? 

I am using Python 2.7.13. 

Thanks,

Hao
```
2020-02-07 16:00:01 - -- starting logging MergeGenotypesStep --
2020-02-07 16:00:03 - ========== Exception ==========
2020-02-07 16:00:03 - Traceback (most recent call last):
2020-02-07 16:00:03 -   File "/nics/e/sw/cs400_centos7.3_acfsoftware/grocsvs/0.2.6/centos7.3_python2.7.13/grocsvs_env/lib/python2.7/site-packages/grocsvs/pipeline.py", line 87, in _run_chunk
2020-02-07 16:00:03 -     chunk.run()
2020-02-07 16:00:03 -   File "/nics/e/sw/cs400_centos7.3_acfsoftware/grocsvs/0.2.6/centos7.3_python2.7.13/grocsvs_env/lib/python2.7/site-packages/grocsvs/stages/genotyping.py", line 56, in run
2020-02-07 16:00:03 -     print row.Index, row.cluster, counts[row.cluster]
2020-02-07 16:00:03 - AttributeError: 'tuple' object has no attribute 'Index'
2020-02-07 16:00:03 - 
2020-02-07 16:00:03 - 'tuple' object has no attribute 'Index'
```

**Comment by nspies** [comment]
Hi Hao,

I haven't touched this code in some years, so I probably won't be much help here. If you've gotten to this step, it looks like you're almost done, so I might suggest playing around a little. You could try adding a `print row` statement immediately after the `for` statement, prior to the offending line. Best guess this is something about the index column not being specified correctly when reading some intermediate files from disk. Are you using the versions of dependencies specified in the requirements.txt (most notably pandas)?

**Comment by chen42** [comment]
Hi, Noah,

I was using a newer version of Pandas. But down grading does not fix the bug from where it was stopped. I am now going to rerun it from the begining. Hope it will be fine.
