### ISSUE TITLE
manually install pybedtools

### ISSUE THREAD

**Issue by stetner** [grocsvs/grocsvs#8]
After removing pygraphviz from the setup.py, it appears I have to manually install pybedtools or I get the error at the bottom.

This works though (anaconda2 4.4.0)
pip uninstall pybedtools
git clone https://github.com/daler/pybedtools.git
cd pybedtools/
pip install .
../grocsvs_env2_44/bin/grocsvs
usage: grocsvs [-h] [--restart FROM-STAGE] [--local] [--multiprocessing]
               [--debug]
               config

Genome-wide Reconstruction of Complex Structural Variants

positional arguments:
  config                Path to configuration.json file

optional arguments:
  -h, --help            show this help message and exit
  --restart FROM-STAGE  restart from this stage
  --local               run locally in single processor mode
  --multiprocessing     run locally using multiprocessing
  --debug               run in debug mode
(grocsvs_env2_44)

$ ../grocsvs_env2_44/bin/grocsvs
Traceback (most recent call last):
  File "../grocsvs_env2_44/bin/grocsvs", line 11, in <module>
    load_entry_point('grocsvs==0.2.6', 'console_scripts', 'grocsvs')()
  File "/shares/common/users/d.stetner/build/grocsvs_env2_44/lib/python2.7/site-packages/pkg_resources/__init__.py", line 563, in load_entry_point
    return get_distribution(dist).load_entry_point(group, name)
  File "/shares/common/users/d.stetner/build/grocsvs_env2_44/lib/python2.7/site-packages/pkg_resources/__init__.py", line 2651, in load_entry_point
    return ep.load()
  File "/shares/common/users/d.stetner/build/grocsvs_env2_44/lib/python2.7/site-packages/pkg_resources/__init__.py", line 2305, in load
    return self.resolve()
  File "/shares/common/users/d.stetner/build/grocsvs_env2_44/lib/python2.7/site-packages/pkg_resources/__init__.py", line 2311, in resolve
    module = __import__(self.module_name, fromlist=['__name__'], level=0)
  File "/shares/common/users/d.stetner/build/grocsvs_env2_44/lib/python2.7/site-packages/grocsvs/main.py", line 9, in <module>
    from grocsvs import options as svoptions
  File "/shares/common/users/d.stetner/build/grocsvs_env2_44/lib/python2.7/site-packages/grocsvs/options.py", line 9, in <module>
    from grocsvs.stages import constants
  File "/shares/common/users/d.stetner/build/grocsvs_env2_44/lib/python2.7/site-packages/grocsvs/stages/__init__.py", line 26, in <module>
    from grocsvs.stages import genotyping
  File "/shares/common/users/d.stetner/build/grocsvs_env2_44/lib/python2.7/site-packages/grocsvs/stages/genotyping.py", line 5, in <module>
    import pybedtools
  File "/shares/common/users/d.stetner/build/grocsvs_env2_44/lib/python2.7/site-packages/pybedtools/__init__.py", line 10, in <module>
    from .cbedtools import (Interval, IntervalFile, overlap, Attributes,
ImportError: /shares/common/users/d.stetner/build/anac2_44/lib/libstdc++.so.6: version `GLIBCXX_3.4.21' not found (required by /shares/common/users/d.stetner/build/grocsvs_env2_44/lib/python2.7/site-packages/pybedtools/cbedtools.so)

**Comment by nspies** [comment]
I haven't tried installing grocsvs through anaconda, and I'm guessing what you're seeing is either an incompatibility between conda and the standard python installation libraries or some peculiarity of your conda env where you had a package/library installed from different places (eg see https://github.com/daler/pybedtools/issues/187).

As noted in the readme, the recommended (and tested) approach for installing grocsvs is using pip and virtualenv. I'm happy to accept pull requests fixing anaconda compatibility but have no experience with anaconda myself.
